name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Change directory to candidly-app
        run: cd candidly-app

      - name: Install dependencies
        working-directory: candidly-app
        run: npm install

      - name: Run tests
        working-directory: candidly-app
        run: npm run test
